# Generated by Django 4.2.13 on 2024-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='puntos',
            field=models.IntegerField(default=2500),
        ),
    ]
