# Generated by Django 4.2.13 on 2024-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='puntos',
            field=models.IntegerField(default=100),
        ),
    ]
