# Generated by Django 4.2.13 on 2024-06-23 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Market', '0002_ship_descripcion_ship_imagen'),
        ('Usuarios', '0003_alter_puntos_puntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.ship')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
