# Generated by Django 4.2.13 on 2024-06-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_ship_descripcion_ship_imagen'),
        ('Usuarios', '0004_naves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naves',
            name='Naves',
        ),
        migrations.AddField(
            model_name='naves',
            name='naves',
            field=models.ManyToManyField(to='Market.ship'),
        ),
    ]
