# Generated by Django 4.2.13 on 2024-06-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_ship_descripcion_ship_imagen'),
        ('Usuarios', '0005_remove_naves_naves_naves_naves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naves',
            name='naves',
        ),
        migrations.AddField(
            model_name='naves',
            name='nave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Market.ship'),
        ),
    ]
